<?php

namespace Database\Seeders;

use App\TrainingCourse;
use App\TrainingSortCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TrainingSeeder extends Seeder {
    /**
     * Seeds training_courses and training_lessons per the ZTL training order.
     * vZTL ARTCC 3120.4K, June 8, 2026
     */
    public function run(): void {
        DB::table('training_courses')->insert([
            [
            'course_id' => 'S1',
            'course_name' => 'Developing Controller',
            'certification' => 1,
            'associated_rating' => 2,
            ],
            [
            'course_id' => 'S2',
            'course_name' => 'Aerodrome Controller',
            'certification' => 1,
            'associated_rating' => 3,
            ],
            [
            'course_id' => 'S3',
            'course_name' => 'Terminal Controller',
            'certification' => 1,
            'associated_rating' => 4,
            ],
            [
            'course_id' => 'C1',
            'course_name' => 'Enroute Controller',
            'certification' => 1,
            'associated_rating' => 5,
            ],
            [
            'course_id' => 'CLT_ATCT',
            'course_name' => 'CLT Tower Cab',
            'certification' => 0,
            'associated_rating' => null,
            ],
            [
            'course_id' => 'CLT_APP',
            'course_name' => 'CLT TRACON',
            'certification' => 0,
            'associated_rating' => null,
            ],
            [
            'course_id' => 'ATL_ATCT',
            'course_name' => 'Atlanta Tower Cab',
            'certification' => 0,
            'associated_rating' => null,
            ],
            [
            'course_id' => 'A80',
            'course_name' => 'Atlanta Large TRACON',
            'certification' => 0,
            'associated_rating' => null,
            ],
            [
            'course_id' => 'VISIT',
            'course_name' => 'Visiting C1 Fast Track',
            'certification' => 0,
            'associated_rating' => null,
            ],
        ]);

        DB::table('training_sort_category')->insert([
            [
            'id' => 100,
            'category_name' => 'ZTL Onboarding',
            'associated_rating' => 2,
            'scheddy_booking_map' => null,
            ],
            [
            'id' => 101,
            'category_name' => 'Unrestricted Clearance',
            'associated_rating' => 2,
            'scheddy_booking_map' => 'dw_zinXmuG7IonJXI1rQi',
            ],
            [
            'id' => 105,
            'category_name' => 'Unrestricted Ground',
            'associated_rating' => 2,
            'scheddy_booking_map' => '_eqqpYXbIpiwQd1OIhgAh',
            ],
            [
            'id' => 109,
            'category_name' => 'Unrestricted Tower',
            'associated_rating' => 3,
            'scheddy_booking_map' => '7wb1RrBA4QG4nFlt5uBlq',
            ],
            [
            'id' => 115,
            'category_name' => 'Unrestricted Approach',
            'associated_rating' => 4,
            'scheddy_booking_map' => 'NSkB0f-OUPIVp3twQcaQE',
            ],
            [
            'id' => 102,
            'category_name' => 'T1 CLT Delivery',
            'associated_rating' => 2,
            'scheddy_booking_map' => 'fmu_2YuEFsh8rrjMQTLjr',
            ],
            [
            'id' => 106,
            'category_name' => 'T1 CLT Ground',
            'associated_rating' => 2,
            'scheddy_booking_map' => 'BOPuWxHulkUipWKuTfmX_',
            ],
            [
            'id' => 111,
            'category_name' => 'T1 CLT Tower',
            'associated_rating' => 3,
            'scheddy_booking_map' => 'z9lDf54LbkdT28qzEsYGs',
            ],
            [
            'id' => 116,
            'category_name' => 'T1 CLT Approach',
            'associated_rating' => 4,
            'scheddy_booking_map' => '8zt9Mbo7cfwObZjr-l6gI',
            ],
            [
            'id' => 104,
            'category_name' => 'T1 ATL Clearance',
            'associated_rating' => 3,
            'scheddy_booking_map' => 'Hu8KNso7I5pjhsGpqOcRm',
            ],
            [
            'id' => 108,
            'category_name' => 'T1 ATL Ground',
            'associated_rating' => 3,
            'scheddy_booking_map' => null,
            ],
            [
            'id' => 113,
            'category_name' => 'T1 ATL Tower',
            'associated_rating' => 3,
            'scheddy_booking_map' => null,
            ],
            [
            'id' => 117,
            'category_name' => 'A80 Departure/Satellite Radar',
            'associated_rating' => 4,
            'scheddy_booking_map' => 'DOrSeznb_40GEpBv59v3N',
            ],
            [
            'id' => 118,
            'category_name' => 'A80 Terminal Arrival Radar',
            'associated_rating' => 4,
            'scheddy_booking_map' => null,
            ],
            [
            'id' => 119,
            'category_name' => 'A80 Arrival Radar',
            'associated_rating' => 4,
            'scheddy_booking_map' => null,
            ],
            [
            'id' => 121,
            'category_name' => 'Atlanta Center',
            'associated_rating' => 5,
            'scheddy_booking_map' => 'xM_xdSHmlCwKZ3ed_-GDx',
            ],
            [
            'id' => 122,
            'category_name' => 'Recurrent Training',
            'associated_rating' => null,
            'scheddy_booking_map' => null,
            ],
            [
            'id' => 124,
            'category_name' => 'Other',
            'associated_rating' => null,
            'scheddy_booking_map' => null,
            ],
            [
            'id' => 125,
            'category_name' => 'Mentor Training',
            'associated_rating' => null,
            'scheddy_booking_map' => null,
            ],
            [
            'id' => 123,
            'category_name' => 'Legacy Category',
            'associated_rating' => null,
            'scheddy_booking_map' => null,
            ],
        ]);

        $courses = TrainingCourse::pluck('id', 'course_id')->toArray();
        $categories = TrainingSortCategory::pluck('id', 'category_name')->toArray();

        DB::table('training_lessons')->insert([
            [
            'id' => 200,
            'course_id' => $courses['S1'],
            'lesson_id' => 'DEL1',
            'lesson_name' => 'Delivery 1',
            'sort_category_id' => $categories['Unrestricted Clearance'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 201,
            'course_id' => $courses['S1'],
            'lesson_id' => 'DEL2',
            'lesson_name' => 'Delivery 2',
            'sort_category_id' => $categories['Unrestricted Clearance'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 202,
            'course_id' => $courses['S1'],
            'lesson_id' => 'DEL3',
            'lesson_name' => 'Delivery 3',
            'sort_category_id' => $categories['Unrestricted Clearance'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 205,
            'course_id' => $courses['S1'],
            'lesson_id' => 'GND1',
            'lesson_name' => 'Ground 1',
            'sort_category_id' => $categories['Unrestricted Ground'],
            'solo' => false,
            'ots' => true,
            'active' => true,
            ],
            [
            'id' => 206,
            'course_id' => $courses['S2'],
            'lesson_id' => 'TWR1',
            'lesson_name' => 'Tower 1',
            'sort_category_id' => $categories['Unrestricted Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 207,
            'course_id' => $courses['S2'],
            'lesson_id' => 'TWR2',
            'lesson_name' => 'Tower 2',
            'sort_category_id' => $categories['Unrestricted Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 208,
            'course_id' => $courses['S2'],
            'lesson_id' => 'TWR3',
            'lesson_name' => 'Tower 3',
            'sort_category_id' => $categories['Unrestricted Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 209,
            'course_id' => $courses['S2'],
            'lesson_id' => 'TWR4',
            'lesson_name' => 'Tower 4',
            'sort_category_id' => $categories['Unrestricted Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 210,
            'course_id' => $courses['S2'],
            'lesson_id' => 'TWR5',
            'lesson_name' => 'Tower 5',
            'sort_category_id' => $categories['Unrestricted Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 211,
            'course_id' => $courses['S2'],
            'lesson_id' => 'TWR6',
            'lesson_name' => 'Tower 6',
            'sort_category_id' => $categories['Unrestricted Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 261,
            'course_id' => $courses['S2'],
            'lesson_id' => 'TWR7',
            'lesson_name' => 'Tower 7',
            'sort_category_id' => $categories['Unrestricted Tower'],
            'solo' => true,
            'ots' => true,
            'active' => true,
            ],
            [
            'id' => 216,
            'course_id' => $courses['S3'],
            'lesson_id' => 'APP1',
            'lesson_name' => 'Approach 1',
            'sort_category_id' => $categories['Unrestricted Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 217,
            'course_id' => $courses['S3'],
            'lesson_id' => 'APP2',
            'lesson_name' => 'Approach 2',
            'sort_category_id' => $categories['Unrestricted Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 218,
            'course_id' => $courses['S3'],
            'lesson_id' => 'APP3',
            'lesson_name' => 'Approach 3',
            'sort_category_id' => $categories['Unrestricted Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 219,
            'course_id' => $courses['S3'],
            'lesson_id' => 'APP4',
            'lesson_name' => 'Approach 4',
            'sort_category_id' => $categories['Unrestricted Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 220,
            'course_id' => $courses['S3'],
            'lesson_id' => 'APP5',
            'lesson_name' => 'Approach 5',
            'sort_category_id' => $categories['Unrestricted Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 221,
            'course_id' => $courses['S3'],
            'lesson_id' => 'APP6',
            'lesson_name' => 'Approach 6',
            'sort_category_id' => $categories['Unrestricted Approach'],
            'solo' => true,
            'ots' => true,
            'active' => true,
            ],
            [
            'id' => 229,
            'course_id' => $courses['C1'],
            'lesson_id' => 'CTR1',
            'lesson_name' => 'Center 1',
            'sort_category_id' => $categories['Atlanta Center'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 260,
            'course_id' => $courses['C1'],
            'lesson_id' => 'CTR2',
            'lesson_name' => 'Center 2',
            'sort_category_id' => $categories['Atlanta Center'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 230,
            'course_id' => $courses['C1'],
            'lesson_id' => 'CTR3',
            'lesson_name' => 'Center 3',
            'sort_category_id' => $categories['Atlanta Center'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 232,
            'course_id' => $courses['C1'],
            'lesson_id' => 'CTR4',
            'lesson_name' => 'Center 4',
            'sort_category_id' => $categories['Atlanta Center'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 233,
            'course_id' => $courses['C1'],
            'lesson_id' => 'CTR5',
            'lesson_name' => 'Center 5',
            'sort_category_id' => $categories['Atlanta Center'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 231,
            'course_id' => $courses['C1'],
            'lesson_id' => 'CTR6',
            'lesson_name' => 'Center 6',
            'sort_category_id' => $categories['Atlanta Center'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 235,
            'course_id' => $courses['C1'],
            'lesson_id' => 'CTR7',
            'lesson_name' => 'Center 7',
            'sort_category_id' => $categories['Atlanta Center'],
            'solo' => true,
            'ots' => true,
            'active' => true,
            ],
            [
            'id' => 203,
            'course_id' => $courses['CLT_ATCT'],
            'lesson_id' => 'CC1',
            'lesson_name' => 'CLT Clearance Delivery',
            'sort_category_id' => $categories['T1 CLT Delivery'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 258,
            'course_id' => $courses['CLT_ATCT'],
            'lesson_id' => 'CC2',
            'lesson_name' => 'CLT Ground',
            'sort_category_id' => $categories['T1 CLT Ground'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 212,
            'course_id' => $courses['CLT_ATCT'],
            'lesson_id' => 'CC3',
            'lesson_name' => 'CLT Local 1',
            'sort_category_id' => $categories['T1 CLT Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 262,
            'course_id' => $courses['CLT_ATCT'],
            'lesson_id' => 'CC4',
            'lesson_name' => 'CLT Local 2',
            'sort_category_id' => $categories['T1 CLT Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 213,
            'course_id' => $courses['CLT_ATCT'],
            'lesson_id' => 'CC5',
            'lesson_name' => 'CLT Tower Cab',
            'sort_category_id' => $categories['T1 CLT Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 225,
            'course_id' => $courses['CLT_APP'],
            'lesson_id' => 'CT1',
            'lesson_name' => 'CLT Satellite and Departure Radar',
            'sort_category_id' => $categories['T1 CLT Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 226,
            'course_id' => $courses['CLT_APP'],
            'lesson_id' => 'CT2',
            'lesson_name' => 'CLT Arrival Radar',
            'sort_category_id' => $categories['T1 CLT Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 223,
            'course_id' => $courses['CLT_APP'],
            'lesson_id' => 'CT3',
            'lesson_name' => 'CLT Final Radar',
            'sort_category_id' => $categories['T1 CLT Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 263,
            'course_id' => $courses['CLT_APP'],
            'lesson_id' => 'CT4',
            'lesson_name' => 'CLT TRACON Combined',
            'sort_category_id' => $categories['T1 CLT Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 227,
            'course_id' => $courses['CLT_APP'],
            'lesson_id' => 'CT5',
            'lesson_name' => 'CLT TRACON',
            'sort_category_id' => $categories['T1 CLT Approach'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 237,
            'course_id' => $courses['ATL_ATCT'],
            'lesson_id' => 'ATL1',
            'lesson_name' => 'Atlanta Clearance Delivery',
            'sort_category_id' => $categories['T1 ATL Clearance'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 239,
            'course_id' => $courses['ATL_ATCT'],
            'lesson_id' => 'ATL2',
            'lesson_name' => 'Atlanta Local 4 and 5',
            'sort_category_id' => $categories['T1 ATL Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 242,
            'course_id' => $courses['ATL_ATCT'],
            'lesson_id' => 'ATL3',
            'lesson_name' => 'Atlanta Local 3 and 4',
            'sort_category_id' => $categories['T1 ATL Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 243,
            'course_id' => $courses['ATL_ATCT'],
            'lesson_id' => 'ATL4',
            'lesson_name' => 'Atlanta Ground North',
            'sort_category_id' => $categories['T1 ATL Ground'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 240,
            'course_id' => $courses['ATL_ATCT'],
            'lesson_id' => 'ATL5',
            'lesson_name' => 'Atlanta Ground Center',
            'sort_category_id' => $categories['T1 ATL Ground'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 259,
            'course_id' => $courses['ATL_ATCT'],
            'lesson_id' => 'ATL6',
            'lesson_name' => 'Atlanta ATCT (local + ground north)',
            'sort_category_id' => $categories['T1 ATL Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 241,
            'course_id' => $courses['ATL_ATCT'],
            'lesson_id' => 'ATL7',
            'lesson_name' => 'Atlanta ATCT Combined',
            'sort_category_id' => $categories['T1 ATL Tower'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 245,
            'course_id' => $courses['A80'],
            'lesson_id' => 'A801',
            'lesson_name' => 'A80 Satellite Radar - SAT',
            'sort_category_id' => $categories['A80 Departure/Satellite Radar'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 246,
            'course_id' => $courses['A80'],
            'lesson_id' => 'A802',
            'lesson_name' => 'A80 Departure Radar - DR',
            'sort_category_id' => $categories['A80 Departure/Satellite Radar'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 248,
            'course_id' => $courses['A80'],
            'lesson_id' => 'A803',
            'lesson_name' => 'A80 Terminal Arrival Radar - TAR 1',
            'sort_category_id' => $categories['A80 Terminal Arrival Radar'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 250,
            'course_id' => $courses['A80'],
            'lesson_id' => 'A804',
            'lesson_name' => 'A80 Terminal Arrival Radar - TAR 2',
            'sort_category_id' => $categories['A80 Terminal Arrival Radar'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 252,
            'course_id' => $courses['A80'],
            'lesson_id' => 'A805',
            'lesson_name' => 'A80 Arrival Radar - AR 1',
            'sort_category_id' => $categories['A80 Arrival Radar'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 253,
            'course_id' => $courses['A80'],
            'lesson_id' => 'A806',
            'lesson_name' => 'A80 Arrival Radar - AR 2',
            'sort_category_id' => $categories['A80 Arrival Radar'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 254,
            'course_id' => $courses['A80'],
            'lesson_id' => 'A807',
            'lesson_name' => 'A80 TAR and AR Combined',
            'sort_category_id' => $categories['A80 Arrival Radar'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 255,
            'course_id' => $courses['A80'],
            'lesson_id' => 'A808',
            'lesson_name' => 'A80 Combined',
            'sort_category_id' => $categories['A80 Arrival Radar'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
            [
            'id' => 270,
            'course_id' => $courses['VISIT'],
            'lesson_id' => 'ZTL1',
            'lesson_name' => 'Atlanta Center',
            'sort_category_id' => $categories['Other'],
            'solo' => false,
            'ots' => false,
            'active' => true,
            ],
        ]);
        // Legacy lessons
        DB::table('training_lessons')->insert([
            [
            'id' => 204,
            'lesson_id' => 'X001',
            'lesson_name' => 'CLT Clearance Delivery',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 214,
            'lesson_id' => 'X002',
            'lesson_name' => 'CLT Tower',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 215,
            'lesson_id' => 'X003',
            'lesson_name' => 'CLT Tower Monitoring',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 222,
            'lesson_id' => 'X014',
            'lesson_name' => 'BHM Tower Training',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 224,
            'lesson_id' => 'X004',
            'lesson_name' => 'CLT Approach',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 228,
            'lesson_id' => 'X005',
            'lesson_name' => 'Atlanta Center',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 234,
            'lesson_id' => 'X006',
            'lesson_name' => 'Atlanta Center Low',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 236,
            'lesson_id' => 'X013',
            'lesson_name' => 'Atlanta Center',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 238,
            'lesson_id' => 'X007',
            'lesson_name' => 'Atlanta Delivery',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 244,
            'lesson_id' => 'ATL8',
            'lesson_name' => 'Atlanta Tower Monitoring',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 247,
            'lesson_id' => 'X008',
            'lesson_name' => 'A80 Departure Radar',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 249,
            'lesson_id' => 'X009',
            'lesson_name' => 'A80 Terminal Arrival Radar',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 251,
            'lesson_id' => 'X010',
            'lesson_name' => 'A80 Terminal Arrival Radar',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 256,
            'lesson_id' => 'X011',
            'lesson_name' => 'A80 Combined Monitoring',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
            [
            'id' => 257,
            'lesson_id' => 'X012',
            'lesson_name' => 'Visitor Training',
            'sort_category_id' => $categories['Legacy Category'],
            'solo' => false,
            'ots' => false,
            'active' => false,
            ],
        ]);
    }
}
