name: browser test

on: [pull_request, workflow_dispatch]
jobs:
  build:
    uses: ZTL-ARTCC/Current_Website/.github/workflows/build.yml@main
    with:
      artifact-name: 'ztl-deploy-artifact-v1'

  dusk:
    runs-on: ubuntu-latest

    env:
      VATSIM_OAUTH_CLIENT: ${{ secrets.VATSIM_DEV_OAUTH_CLIENT }}
      VATSIM_OAUTH_SECRET: ${{ secrets.VATSIM_DEV_OAUTH_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE \`codecourse_testing\` character set UTF8mb4 collate utf8mb4_bin;"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ needs.setup-variables.outputs.php-version }}

      - name: Copy .env
        run: cp .env.test .env

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate

      - name: Install Chrome binaries
        run: php artisan dusk:chrome-driver --detect

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php artisan serve --no-reload &

      - name: Execute tests
        run: php artisan dusk

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: console
          path: tests/Browser/console
