name: create-release

on: workflow_dispatch

jobs:
  setup-variables:
    uses: ZTL-ARTCC/Current_Website/.github/workflows/setup-variables.yml@main

  tag:
    name: tag and release main
    runs-on: "ubuntu-latest"
    needs: setup-variables
    env:
      TAG: ${{ needs.setup-variables.outputs.tag-name }}

    steps:
      - name: tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.TAG }}",
              sha: context.sha
            })

      - name: release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ env.TAG }}",
              name: "${{ env.TAG }}",
              generate_release_notes: true
            })

      - name: provide tag and release info
        env:
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        run: |
          echo "# Tagged Release" >> $GITHUB_STEP_SUMMARY
          echo "[$TAG]($REPO_URL/releases/tag/$TAG)" >> $GITHUB_STEP_SUMMARY

