name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: tagged release
    runs-on: "ubuntu-latest"

    steps:
      - name: build
        uses: ZTL-ARTCC/Current_Website/.github/workflows/build.yml@main
        with:
          artifact-name: 'ztl-deploy-artifact-v1'

      - name: release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
